apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sdu-evac-backend
  template:
    metadata:
      labels:
        app: sdu-evac-backend
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/sdu-evacuation-project/evac-registry/sdu-evac-backend:v0.1.0
        name: sdu-evac-backend
        env:
        - name: PORT
          value: "80"
        - name: MONGO_DB_CONNECTION_STRING
          value: mongodb+srv://akirk20:R712HfLiQuMAZKWv@cluster0.cfoqsha.mongodb.net/?retryWrites=true&w=majority
        - name: MONGO_DB_NAME
          value: CloudProjectDB
        - name: REDIS_URI
          value: default:GZjFApP6G14dVs3cod3Xb0TBh8KxBg43@redis-13602.c228.us-central1-1.gce.cloud.redislabs.com:13602
